### ISSUE TITLE
How to omit some tables when doing database schema extraction 

### ISSUE THREAD

**Issue by AVE-cesar** [jaxio/celerio#1]
I would like to be able to filter tables that I don't want when  I am doing  database schema extraction.

Is there a way to do it ?

I would appreciate a parameter (with wilcard) that can be used to tell you tool table names we don't want JPA classes to be generated and so on.

**Comment by nromanetti** [comment]
Use the celerio bootstrap to initiate a project.
Then open the `src/main/config/celerio-maven-plugin/celerio-maven-plugin.xml` file

You can configure which tables are used:

``` xml
        <tables>
            <!-- <table include="false" pattern="*_AUDIT"/> -->
            <table include="true" pattern="*"/>
        </tables>
```

**Comment by AVE-cesar** [comment]
thanks

have you ever heard about this tool named jhipster ?

**Comment by nromanetti** [comment]
sure, check out this...https://github.com/jaxio/jhipser-lab
