### ISSUE TITLE
Problems with relationshps between tables from diferent schemas

### ISSUE THREAD

**Issue by sergiofm** [jaxio/celerio#5]
Hi there!

Sory to bother you again, but we have a issue with multiple schemas.
We have relationships between tables from diferent schemas of the same catalog, but this relations don't appear in the metadata.xml
Do we need to do some configuration for this case?
I have not found something related to this case in the documentation.

Thank you!

**Comment by nromanetti** [comment]
No, this is a current limitation... I'll try to work on it and release snapshots that I'll need you to test...

**Comment by sergiofm** [comment]
I'll be glad to test it out!
If you guide me, I can try to work on this limitation too.

**Comment by nromanetti** [comment]
It's rather simple, in [MetadataExtractor](https://github.com/jaxio/celerio/blob/master/celerio-engine/src/main/java/com/jaxio/celerio/configuration/database/support/MetadataExtractor.java) when calling the jdbc metadata api we do not properly pass the catalog and schema name (we should pass the one held by the Table instance) and also we have a map that uses a table name as key... it should use the catalog-schema-table name as key.... then we must propagate these changes to the calling code and test

**Comment by nromanetti** [comment]
actually, not so obvious... it's a bit a mess. Anyway I have just committed some changes, could you build yourself and test on your schemas?

**Comment by sergiofm** [comment]
I've tested here and it worked well!

**Comment by nromanetti** [comment]
Excellent, I'll prepare a new release in a few days :)

**Comment by nromanetti** [comment]
fixed in Celerio 4.0.22
http://www.jaxio.com/documentation/celerio/changelog.html
Thanks for reporting/testing it 👍
